### ISSUE TITLE
Incompatible with ofxstatement 0.6.5

### ISSUE THREAD

**Issue by mlaitinen** [mlaitinen/ofxstatement-revolut#11]
`ofxstatement-revolut` doesn't work with `ofxstatement` version `0.6.5` because of this line: https://github.com/kedder/ofxstatement/commit/e536af21efbfadff56b59cd1938ae822b101aa90#diff-767580eeecc70064922b1880b8ddaf7bR152

None of those fields are set.

Workaround: use `ofxstatement` version `0.6.4`.

**Comment by popelop** [comment]
thx for your commitment.
Feel free to ask me if you need testing. I can help you for french compatibility also.
