### ISSUE TITLE
unable to parse french statement

### ISSUE THREAD

**Issue by popelop** [mlaitinen/ofxstatement-revolut#12]
Hello, 
I'm trying to use the revolut plugin on my statement. 
First of all in edited the ofxstatement config file in order to modify the format date to '%%d %%b. %%Y'
Then i modified the header of the csv statement file (when it is translated in english, it complies with the May 2018 signature in .../plugins/revolut.py). 

Here is the content of my config file: 
```
[revolut]
plugin = revolut
date_format = %%d %%b. %%Y
account = revolut_account
currency = EUR
```

Then when i execute the code i have the following exception: 

```
$ ofxstatement convert -t revolut testfile.csv res.csv
        
Traceback (most recent call last):
  File "/donnees/informatique/anaconda/bin/ofxstatement", line 8, in <module>
    sys.exit(run())
  File "/donnees/informatique/anaconda/lib/python3.7/site-packages/ofxstatement/tool.py", line 195, in run
    return args.func(args)
  File "/donnees/informatique/anaconda/lib/python3.7/site-packages/ofxstatement/tool.py", line 166, in convert
    statement = parser.parse()
  File "/donnees/informatique/anaconda/lib/python3.7/site-packages/ofxstatement/parser.py", line 49, in parse
    stmt_line.assert_valid()
  File "/donnees/informatique/anaconda/lib/python3.7/site-packages/ofxstatement/statement.py", line 158, in assert_valid
    assert self.id or self.check_no or self.refnum
AssertionError
```
Here is the content of testfile.csv:

```
Completed Date ; Description ; Paid Out (EUR) ; Paid In (EUR) ; Exchange Out; Exchange In; Balance (EUR); Category; Notes
08 nov. 2020 ; Rayon Bio       4894386  ; 1,77 ;  ;  ;  ; 1 270,39; Courses; 
7 nov. 2020 ; Grand Frais  ; 29,18 ;  ;  ;  ; 1 272,16; Courses; 
7 nov. 2020 ; Art Prog  ; 20,75 ;  ;  ;  ; 1 301,34; Services;
 ```

I use `ofxstatement 0.7.1`

Hope this help. This plugin may be so usefull for many people who want to use gnucash-like softwares with their revolut files.
Thx :)

**Comment by mlaitinen** [comment]
Hi! This is related to #11. I haven't had the time to make this plugin compatible with ofxstatement >= 0.6.5.

Hopefully I'd have time soon because I hate being stuck on an old version.
