### ISSUE TITLE
Pip installs old version of ofxstatement-revolut (1.6.0)

### ISSUE THREAD

**Issue by yasmans** [mlaitinen/ofxstatement-revolut#18]
When installing **ofxstatement-revolut** package older version is selected. 

>~/> pip3 install ofxstatement-revolut==2.0.0                            
> Defaulting to user installation because normal site-packages is not writeable
> ERROR: Could not find a version that satisfies the requirement ofxstatement-revolut==2.0.0 (from versions: 1.2.0, 1.3.1, 1.4.0, 1.6.0)
> ERROR: No matching distribution found for ofxstatement-revolut==2.0.0

Version 2.0.0 of this package is published as .egg and it is not supported by pip. [installation_log.txt](https://github.com/mlaitinen/ofxstatement-revolut/files/7815191/installation_log.txt)

Here is a discussion on similar  problem: [link](https://stackoverflow.com/questions/41757965/pip-installs-old-version-of-package

**Comment by mlaitinen** [comment]
So _that's_ what's up. Hmm. I noticed something weird when I published 2.0.0.

I'll try to package and publish it again.

Paldies!
