### ISSUE TITLE
Account currency

### ISSUE THREAD

**Issue by archont00** [mlaitinen/ofxstatement-revolut#2]
Hi,

Any chance to set parser.statement.currency as per currency code in the header line of the CSV file Paid Out (CCY)?

That would limit the configuration to a single entry for all the currencies Revolut supports.

P.S. And the signature matching would have to be more general.

**Comment by archont00** [comment]
Tried something to resolve this issue: https://github.com/mlaitinen/ofxstatement-revolut/pull/5

**Comment by mlaitinen** [comment]
Closed by #5
