### ISSUE TITLE
Date format?

### ISSUE THREAD

**Issue by archont00** [mlaitinen/ofxstatement-revolut#3]
Hi,

the `class RevolutCSVStatementParser(CsvStatementParser):` sets `date_format = "%b %d, %Y"`.

This might be somewhat dependent on OS language settings and language variants Revolut app supports:

    English / UK: 18 May 2018
    Deutsch / Deutschland: 18.05.2018
    Czech: May 18, 2018 (obviously not Czech, but rather English US style).

Any ideas how to deal with that? A dictionary to allow user set his own format?

**Comment by mlaitinen** [comment]
Really? Can you change the date format in the CSV from Revolut?

My preferred date format would be the German one, but I'm under the impression that the date format in the CSV is completely in the hands of Revolut.

**Comment by archont00** [comment]
Indeed. Try to change the phone language. (There is nothing to be changed in Revolut.) Trial & Error tells me that if Revolut does not support that language, it sets the English US style date format.

At least, this is how it works on Android.
