### ISSUE TITLE
Adding this package to Pip registry

### ISSUE THREAD

**Issue by FnTm** [mlaitinen/ofxstatement-revolut#4]
Hey there! 

I'm not super well versed in how the Pip registry works, but trying to just `pip install ofxstatement-revolut` doesn't do it for me, and it feels like it should. I'm currently using a workaround by pulling straight from Github ([example of that](https://github.com/FnTm/ofxstatement-lv/blob/master/requirements.txt#L3)), but I'd like to be able to just do the pip command route. 

Could you please upload the package to the appropriate registries?

**Comment by mlaitinen** [comment]
That's a great idea! I have never done that before, but I'll look into it.

**Comment by mlaitinen** [comment]
Ok, done! `pip3 install ofxstatement-revolut` works now.

**Comment by FnTm** [comment]
Awesome, thanks @mlaitinen!
